### PR TITLE
f95 error

### PR DESCRIPTION
**Pull request by christopherlovell**
added f95 error to troubleshooting section

### CODE REVIEW

**Comment by dnarayanan** [comment]
thanks!

**Comment by dnarayanan** [comment]
oh i realized the readthedocs may not link to the github repo - will update this either today or monday (on travel right now)

**Comment by christopherlovell** [comment]
safe travels!

**Comment by dnarayanan** [comment]
think i got it - let me know if it doesn't seem to update!

**Comment by christopherlovell** [comment]
updated for me on readthedocs, cheers

**Pull request merged**
