### PR TITLE
rescale masses from cluster mass distribution function

### PR DESCRIPTION
**Pull request by christopherlovell**
`cmdf` currently returns samples from the cluster mass distribution function, but these may not sum exactly to the initial mass (`stellar_mass`). Added (optional) functionality scales the masses to sum exactly to the initial stellar mass. Currently set to default to original functionality; rescaled masses can be chosen by setting `rescale_masses = True`

### CODE REVIEW

**Comment by dnarayanan** [comment]
oh this is a good fix - thanks for issuing this!  

it seems like we might want the default to be `rescale_masses=True` and that the fact that it hadn't summed to the initial mass is a bug.  is there any obvious reason not to set the default as `True`?

**Comment by christopherlovell** [comment]
The only thing I'm worried about is whether there are any knock on effects due to the fact that the masses will then be outside the range of `cmdf_min_mass` and `cmdf_max_mass`. So I set it as optional for the moment, until we can verify it's not going to break anything else(!) but could just set it on by default

**Comment by christopherlovell** [comment]
Once #110 is merged I will add flags to the parameter file for this and resubmit

**Comment by dnarayanan** [comment]
thanks!  I merged #110 just now so happy for the updated parameter files.

**Pull request merged**
